### ISSUE TITLE
Container::get return type

### ISSUE THREAD

**Issue by King2500** [klesun/deep-assoc-completion#67]
We use Symfony DI Container and your plugin shows methods, which do not really exist:

![image](https://user-images.githubusercontent.com/4896363/54218792-7f4a6d00-44ee-11e9-9909-acd1f6b0af72.png)

Why are these "methods" attached? The `get` method of `Container(Interface)` returns the actual objects, not an instance of the container itself or anything else...

Thank you for your reply

**Comment by klesun** [comment]
Hi.
The completion comes from the `Symfony\Component\DependencyInjection\Container::get()` which is resolved as one of implementations of `ContainerInterface` and has such code:
```php
public function get($id, $invalidBehavior = /* self::EXCEPTION_ON_INVALID_REFERENCE */ 1)
{
    return $this->services[$id]
        ?? $this->services[$id = $this->aliases[$id] ?? $id]
        ?? ('service_container' === $id ? $this : ($this->factories[$id] ?? [$this, 'make'])($id, $invalidBehavior));
}
```
And since in some cases it returns `$this` plugin resolves `$container->get()` as `Container`.

**Comment by klesun** [comment]
I would love to grey out such irrelevant options or exclude them altogether, but I can't think of a way to tell them apart from actually usefull options.

I could add a behavior that would fix this particular case: when we know the actual string value (`NewsRepository::class`) and the returned value depends on it - to cut off values that will never happen (`NewsRepository::class !== 'service_container'`). But I bet this won't cover all cases where framework returns something generic in some nasty `elseif`...

**Comment by King2500** [comment]
1. The only situation when `Container` is returned, is when you call with `...->get('service_container')`.
But this situation is rare. When you already have access to the container with `$container->get` you dont need the container from itself..
2. This is already covered by [Symfony plugin](https://github.com/Haehnchen/idea-php-symfony2-plugin). I don't understand why this is needed to be covered by "assoc completion" plugin ;-)

**Comment by klesun** [comment]
Whoa, this symfony plugin is cool. And my plugin seems to conflict with it very badly ;c.... I made few patches to not override it's features. My method completion options will be greyed out and in the bottom of the list from now on.
[2019.03.24.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/59858)

![image](https://user-images.githubusercontent.com/5202330/54882921-12709480-4e57-11e9-8c06-44c97a83ca31.png)

**Comment by King2500** [comment]
Ok, thanks.

But i still don't understand why you add those method completion at all. It makes no sense to me :)
